<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="table" params="prefix parent *origin">
    <xacro:property name="table_length" value="0.5" />
    <xacro:property name="table_width" value="0.5" />
    <xacro:property name="table_height" value="1.0" />
    <xacro:property name="table_thickness" value="0.05" />
    <xacro:property name="leg_length" value="${table_height - table_thickness}" />
    <xacro:property name="leg_radius" value="0.05" />


    <link name="table_top">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0" />
        <geometry>
          <box size="${table_length} ${table_width} ${table_thickness}" />
        </geometry>
        <material name="brown" />
      </visual>
    </link>

    <joint name="wtable" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="table_top"/>
    </joint>

    <link name="leg1">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0.5" />
        <geometry>
          <cylinder radius="${leg_radius}" length="${leg_length}"/>
        </geometry>
        <material name="light_grey" />
      </visual>
    </link>

    <!-- joint from "world" to "base_link"-->
    <joint name="w00" type="fixed">
      <origin rpy="0 0 0" xyz="${table_length/2 - leg_radius} ${table_width/2 - leg_radius} -${table_height}" />
      <parent link="table_top" />
      <child link="leg1" />
    </joint>



    <link name="leg3">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0.5" />
        <geometry>
          <cylinder radius="${leg_radius}" length="${leg_length}"/>
        </geometry>
        <material name="light_grey" />
      </visual>
    </link>

    <!-- joint from "world" to "base_link"-->
    <joint name="w10" type="fixed">
      <origin rpy="0 0 0" xyz="-${table_length/2 - leg_radius} ${table_width/2 - leg_radius} -${table_height}" />
      <parent link="table_top" />
      <child link="leg3" />
    </joint>



    <link name="leg2">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0.5" />
        <geometry>
          <cylinder radius="${leg_radius}" length="${leg_length}"/>
        </geometry>
        <material name="light_grey" />
      </visual>
    </link>

    <!-- joint from "world" to "base_link"-->
    <joint name="w01" type="fixed">
      <origin rpy="0 0 0" xyz="${table_length/2 - leg_radius} -${table_width/2 - leg_radius} -${table_height}" />
      <parent link="table_top" />
      <child link="leg2" />
    </joint>

    <link name="leg4">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0.5" />
        <geometry>
          <cylinder radius="${leg_radius}" length="${leg_length}"/>
        </geometry>
        <material name="light_grey" />
      </visual>
    </link>

    <!-- joint from "world" to "base_link"-->
    <joint name="w11" type="fixed">
      <origin rpy="0 0 0" xyz="-${table_length/2 - leg_radius} -${table_width/2 - leg_radius} -${table_height}"/>
      <parent link="table_top" />
      <child link="leg4" />
    </joint>




  </xacro:macro>

</robot>